stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/data_ingestion_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifact/data_ingestion/kidney-ct-scan-image


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/prepare_base_model_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/prepare_base_model_pipeline.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifact/prepare_base_model


  training:
    cmd: python src/cnnClassifier/pipeline/model_training_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/model_training_pipeline.py
      - config/config.yaml
      - artifact/data_ingestion/kidney-ct-scan-image
      - artifact/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifact/training/model.h5


  evaluation:
    cmd: python src/cnnClassifier/pipeline/model_evaluation_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/model_evaluation_pipeline.py
      - config/config.yaml
      - artifact/data_ingestion/kidney-ct-scan-image
      - artifact/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - artifact/score/scores.json:
        cache: false