artifact_root: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  source_url: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  # source_url: https://drive.google.com/file/d/1cYbDuSWZt_9ISX1_e7c7WVPhMwybw_P2/view?usp=drive_link
  local_data_file: artifact/data_ingestion/data.zip
  unzip_dir: artifact/data_ingestion

prepare_base_model:
  root_dir: artifact/prepare_base_model
  base_model_path: artifact/prepare_base_model/base_model.h5
  updated_base_model_path: artifact/training/base_model_updated.h5


training:
  root_dir: artifact/training
  trained_model_path: artifact/training/model.h5